# -*- coding: utf-8 -*-
"""python-expense-tracker.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fFRO_ErV3IIBWPGvELfzcUO-RNU_mUSC
"""

expenses = []

def add_expense():
    amount = float(input("Enter amount: "))
    category = input("Enter category: ")
    expenses.append({"amount": amount, "category": category})
    print("Expense added!")

def view_expenses():
    total = 0
    for expense in expenses:
        print(expense)
        total += expense["amount"]
    print("Total expense:", total)

while True:
    print("\n1. Add Expense")
    print("2. View Expenses")
    print("3. Exit")

    choice = input("Choose option: ")

    if choice == "1":
        add_expense()
    elif choice == "2":
        view_expenses()
    elif choice == "3":
        break
    else:
        print("Invalid choice")